create table if not exists mpa_rating (
    mpa_rating_id integer generated by default as identity primary key,
    name varchar(255) not null
    );

create table if not exists films (
    film_id integer generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(200),
    release_date date,
    duration integer,
    mpa_rating_id integer not null references mpa_rating (mpa_rating_id)
    );

create table if not exists users (
    user_id integer generated by default as identity primary key,
    email varchar(255) not null unique,
    login varchar(255) not null,
    name varchar(255),
    birthday date
    );

create table if not exists user_likes (
    film_id integer not null references films (film_id) on delete cascade,
    user_id integer not null references users (user_id) on delete cascade,
    primary key (film_id, user_id)
    );

create table if not exists genres (
     genre_id integer generated by default as identity primary key,
     name varchar(255) not null
    );

create table if not exists film_genres (
    film_id integer not null references films (film_id) on delete cascade,
    genre_id integer not null references genres (genre_id) on delete cascade,
    primary key (film_id, genre_id)
    );

create table if not exists friendship_status (
    status_id integer generated by default as identity primary key,
    name varchar(255) not null
    );

create table if not exists friends (
    user_id integer not null references users (user_id) on delete cascade,
    friend_id integer not null references users (user_id) on delete cascade,
    status_id integer not null references friendship_status (status_id) on delete restrict,
    primary key (user_id, friend_id)
    );

UPDATE genres SET name = 'COMEDY' WHERE genre_id = 1;
UPDATE genres SET name = 'DRAMA' WHERE genre_id = 2;
UPDATE genres SET name = 'CARTOON' WHERE genre_id = 3;
UPDATE genres SET name = 'THRILLER' WHERE genre_id = 4;
UPDATE genres SET name = 'DOCUMENTARY' WHERE genre_id = 5;
UPDATE genres SET name = 'ACTION' WHERE genre_id = 6;
